from katago.clean_sgf_add_comments_for_endpoint import clean_sgf
from sgfmill import sgf


def test_clean_sgf():

  ''' Removes various properties from original SGF, the most important being the comment properties
      since Glift uses comments to determine if the click is a correct or incorrect answer.
      Also, the sgf is destroyed from the puzzle move number onwards, so that Glift doesn't just play out the whole game after a user clicks on the board.
      Finally this functions also removes various other properties, like those found from Fox Go server, that Glift and FF[4] agree are invalid'''

  # sgf_data with lots of comments, invalid properties, and random text everywhere from KaTrain analysis
  sgf_data = "(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2] RU[Chinese]SZ[19]KM[7.50]TM[300] GN[]PW[青瓦楼阁]PB[anning97]DT[2023-07-09]C[SGF generated by KaTrain 1.12.3ㅤ​]RE[B+Resign]KTV[1.0]RL[0]RN[3]TC[3]TT[30] ;B[qd] ;W[dp] ;B[pq] ;W[dd] ;B[cc] ;W[dc] ;B[cd] ;W[ce] ;B[be] ;W[bf] ;B[cf] ;W[de] ;B[bg] ;W[bd] ;B[af] ;W[bc] ;B[nc] ;W[qo] ;B[ql] ;W[op] ;B[oq] ;W[np] ;B[mr] ;W[lq] ;B[mq] ;W[mp] ;B[lp] ;W[kq] ;B[lo] ;W[rq] ;B[qr]C[Move 31: B R2 Score: W+3.9 Win rate: W 71.1% Estimated point loss: 4.3 Predicted top move was S2 (B+0.5). PV: BS2 K4 O6 P6 P7 O7 Q6 P5 P8 R3 R2 M6 Move was #96 according to policy (0.00%). Top policy move was K4 (40.0%). ㅤ​] ;W[rr] ;B[lr] ;W[kr] ;B[nq]C[Move 35: B O3 Score: W+8.9 Win rate: W 87.0% Estimated point loss: 4.4 Predicted top move was J4 (W+4.2). PV: BJ4 K4 K5 J3 H4 H3 G3 G4 G2 J5 H5 L5 J6 M6 N5 L4 Move was #33 according to policy (0.03%). Top policy move was J4 (29.8%). ㅤ​] ;W[on] ;B[jp] ;W[iq] ;B[ip] ;W[hq] ;B[go] ;W[fp] ;B[ol] ;W[nm] ;B[mk] ;W[rd] ;B[re] ;W[qc] ;B[rc] ;W[pd] ;B[qe] ;W[rb] ;B[sd] ;W[pe] ;B[pc] ;W[oc] ;B[qb] ;W[nd] ;B[ob] ;W[od]C[Move 60: W P16 Score: W+5.4 Win rate: W 78.3% Estimated point loss: 4.8 Predicted top move was M7 (W+10.4). PV: WM7 K7 L8 K8 L9 K9 L10 N12 Move was #134 according to policy (0.01%). Top policy move was M7 (32.0%). ㅤ​] ;B[mc] ;W[md] ;B[ld] ;W[le] ;B[ke] ;W[kf]C[Move 66: W L14 Score: W+0.5 Win rate: W 55.3% Estimated point loss: 5.4 Predicted top move was M14 (W+6.0). PV: WM14 F5 E5 L14 M13 P13 L13 L16 M7 K7 L9 Move was #3 according to policy (1.72%). Top policy move was M14 (75.8%). ㅤ​] ;B[kd])"
  # Hard code the puzzle move for this test case, we are dynamically grabbing this in our process_katago_output function where we pass in the json_output showing the move number of the mistake(s)
  move_number = 31
  # Clean SGF string
  cleaned_sgf_string = clean_sgf(sgf_data, move_number)
  print("Cleaned sgf string", cleaned_sgf_string)

  # Check using sgfmill
  try:
      sgf_game = sgf.Sgf_game.from_string(cleaned_sgf_string)
  except ValueError as e:
      assert False, f"SGF parsing failed: {e}"

  root_node = sgf_game.get_root()
  properties = root_node.get_raw_property_map()

  # Check for comments, those are the main culprit if glift fails to render the puzzle correctly
  if 'C' in properties or 'GC' in properties:
      assert False, "SGF contains comments."

  # Expected output
  expected_cleaned_sgf = "(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]RU[Chinese]SZ[19]KM[7.50]TM[300]GN[]PW[青瓦楼阁]PB[anning97]DT[2023-07-09]RE[B+Resign];B[qd];W[dp];B[pq];W[dd];B[cc];W[dc];B[cd];W[ce];B[be];W[bf];B[cf];W[de];B[bg];W[bd];B[af];W[bc];B[nc];W[qo];B[ql];W[op];B[oq];W[np];B[mr];W[lq];B[mq];W[mp];B[lp];W[kq];B[lo];W[rq];B[qr])"

  assert cleaned_sgf_string == expected_cleaned_sgf
